# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Life is short
tagline:             'This doodler'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://ryancat.github.io
baseurl:             ''
paginate:            2

# About/contact
author:
  name:              Ryan Chen
  url:               https://www.linkedin.com/in/xchan
  email:             xryanchen@gmail.com

# Custom vars
version:             1.0.0
